apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-multitool
  name: nginx-multitool
spec:
  ports:
  - name: nginx
    port: 9001
    protocol: TCP
    targetPort: 80
  - name: port-2
    port: 9002
    protocol: TCP
    targetPort: 1180
  selector:
    app: nginx-multitool